---
apiVersion: v1
kind: Namespace
metadata:
  name: website
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: website
  namespace: website
  labels:
    k8s-app: website
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: website
  template:
    metadata:
      labels:
        k8s-app: website
        name: website
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: carloshn/website
        name: website
        ports:
        - name: http
          containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: website
  namespace: website
spec:
  selector:
    k8s-app: website
  ports:
    - protocol: TCP
      port: 80
      name: web
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: website
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service: 
              name: website
              port:
                number: 80
