apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
   - ../base

patches:
  - patches/frontend.yml

commonLabels:
    env: stg

replicas:
  - name: website
    count: 1

#configMapGenerator:
#  - name: website
#    namespace: website
#    behavior: merge
#    envs:
#      - configs/frontend_variables.env
